export const sample_foods: any[] = [
  {
    id: "1",
    name: "Ямакаси",
    cookTime: "20-30",
    price: 390.0,
    favorite: false,
    stars: 4.8,
    imageUrl: "assets/yamakasi.png",
    tags: ["Роллы", "Теплые роллы"],
  },
  {
    id: "2",
    name: "Панко",
    price: 390.0,
    cookTime: "20-30",
    favorite: true,
    stars: 4.7,
    imageUrl: "assets/panko.png",
    tags: ["Роллы", "Теплые роллы"],
  },
  {
    id: "3",
    name: "Филадельфия",
    price: 390.0,
    cookTime: "20-30",
    favorite: false,
    stars: 4.5,
    imageUrl: "assets/philadelphia.png",
    tags: ["Роллы"],
  },
  {
    id: "4",
    name: "Том-Ям",
    price: 350.0,
    cookTime: "40-50",
    favorite: true,
    stars: 4.3,
    imageUrl: "assets/tom-yam.png",
    tags: ["Супы"],
  },
  {
    id: "5",
    name: "Мисо суп",
    price: 170.0,
    cookTime: "40-50",
    favorite: false,
    stars: 5.0,
    imageUrl: "assets/miso-soup.png",
    tags: ["Супы"],
  },
  {
    id: "6",
    name: "Дракон",
    price: 500.0,
    cookTime: "40-50",
    favorite: false,
    stars: 4.9,
    imageUrl: "assets/drakon.png",
    tags: ["Роллы"],
  },
];

export const sample_tags: any[] = [
  { name: "Роллы", count: 4 },
  { name: "Теплые роллы", count: 2 },
  { name: "Супы", count: 2 },
];

export const sample_users: any[] = [
  {
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: true,
  },
  {
    name: "Jane Doe",
    email: "Jane@gmail.com",
    password: "12345",
    address: "Shanghai",
    isAdmin: false,
  },
];
